---

- hosts: all
  become: true
  tasks:
  - name: update repo index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: absent
  - name: install more packages
    apt: name={{ item }} update_cache=yes state=absent
    with_items:
      - php5-cli
      - php5-curl
      - php5-fpm
      - php5-intl
      - php5-json
      - php5-mcrypt
      - php5-sqlite
